version: '3.8'
services:
  back:
    build: ./back
    ports:
      - "3000:3000"
    working_dir: /fastapi_app
    volumes:
      - ./db/items.db:/fastapi_app/db/items.db
    environment:
      - DATABASE_URL=sqlite:///./db/items.db
    networks:
      - fastapi_network
    restart: always
  front:
    build: ./front
    ports:
      - "8000:8000"
    working_dir: /fastapi_app
    networks:
      - fastapi_network
    restart: always
    depends_on:
      - back
    environment:
      - BACKEND_URL=http://back:3000
networks:
  fastapi_network:
    driver: bridge
